"""empty message

Revision ID: 6b91c9e78bee
Revises: bdf7883062c3
Create Date: 2024-07-17 13:31:32.077804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b91c9e78bee'
down_revision = 'bdf7883062c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('demo',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('demo',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
